SELECT * FROM TAB;
SELECT * FROM STUDENT;

-- [문제] 화학과를 제외하고 학과별로 학생들의 평점 평균을 검색하세요
SELECT MAJOR AS 학과, ROUND(AVG(AVR), 2) AS "평점 평균"
FROM STUDENT GROUP BY MAJOR HAVING MAJOR != '화학';

-- [문제] 화학과를 제외한 각 학과별 평균 평점 중에 평점이 2.0 이상인 정보를 검색하세요
SELECT MAJOR FROM STUDENT
GROUP BY MAJOR HAVING MAJOR != '화학' AND AVG(AVR) >= 2.0;

-- 문제1) 송강 교수가 강의하는 과목을 검색한다
-- 테이블: PROFESSOR P, COURSE C
SELECT * FROM PROFESSOR;
SELECT * FROM COURSE;
SELECT P.PNO, PNAME, CNO, CNAME FROM PROFESSOR P, COURSE C
WHERE P.PNO=C.PNO AND PNAME='송강';
-- JOIN 사용
SELECT PNO, PNAME, CNO, CNAME
FROM COURSE JOIN PROFESSOR USING(PNO) WHERE PNAME='송강';

-- 문제2) 화학 관련 과목을 강의하는 교수의 명단을 검색한다
-- 테이블: PROFESSOR P, COURSE C
-- 컬럼 : PNO, PNAME, CNO, CNAME
SELECT PNAME, CNO, CNAME FROM PROFESSOR P, COURSE C
WHERE P.PNO=C.PNO AND CNAME LIKE '%화학%';

-- 문제3) 화학과 1학년 학생의 기말고사 성적을 검색한다
-- 테이블 : STUDENT ST, SCORE SC, COURSE CO
-- 컬럼 : SNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
SELECT * FROM STUDENT;
SELECT * FROM SCORE;
SELECT * FROM COURSE;
SELECT SC.SNO, SNAME, MAJOR, SYEAR, SC.CNO, CNAME, RESULT
FROM STUDENT ST, SCORE SC, COURSE CO
WHERE ST.SNO=SC.SNO AND SC.CNO=CO.CNO AND MAJOR='화학' AND SYEAR=1;
-- JOIN 사용
SELECT SNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
FROM STUDENT
JOIN SCORE USING(SNO)
JOIN COURSE USING(CNO)
WHERE MAJOR='화학' AND SYEAR=1;

-- 문제4) 화학과 1학년 학생의 일반화학 기말고사 점수를 검색한다
-- 테이블 : STUDENT ST, SCORE SC, COURSE CO
-- 컬럼 : SNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
SELECT ST.SNO, SNAME, MAJOR, SYEAR, SC.CNO, CNAME, RESULT
FROM STUDENT ST, SCORE SC, COURSE CO
WHERE ST.SNO = SC.SNO AND SC.CNO = CO.CNO AND MAJOR='화학' AND CNAME='일반화학' AND SYEAR=1;
-- JOIN 사용
SELECT SNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
FROM STUDENT
JOIN SCORE USING(SNO)
JOIN COURSE USING(CNO)
WHERE MAJOR='화학' AND CNAME='일반화학' AND SYEAR=1;