-- [문제1] 최저급여를 받는 사원들의 이름과 급여를 구하시오
SELECT * FROM EMPLOYEES;
-- 내가 쓴 코드
SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY <ANY(SELECT SALARY FROM EMPLOYEES);
-- 답
SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

-- [문제2] 부서별 급여 합계 중 최대급여를 받는 부서의 부서명과 급여합계를 구하시오
SELECT * FROM TAB;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
-- 내가 쓴 코드
SELECT SUM(SALARY) AS "부서별 급여 합계" FROM EMPLOYEES GROUP BY DEPARTMENT_ID
WHERE SUM(SALARY)= (SELECT MAX(SUM(SALARY)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);
-- 답

